import re

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory


KATA_PENTING = ['tidak', 'bukan', 'belum', 'kurang', 'jangan', 'sangat', 'lebih']
CUSTOM_STOPWORD = ['bang',
 'om',
 'min',
 'bro',
 'gan',
 'ngab',
 'kak',
 'nya',
 'sih',
 'kok',
 'dong',
 'deh',
 'lah',
 'mah',
 'pun',
 'kan',
 'bjir',
 'anjir',
 'njir',
 'buset',
 'halo',
 'hai',
 'lur']
KAMUS_SLANG = {'abg': 'abang',
 'aj': 'saja',
 'aja': 'saja',
 'ajah': 'saja',
 'aku': 'saya',
 'alhamdulila': 'syukur',
 'alhamdulilah': 'syukur',
 'alhamdulillah': 'syukur',
 'allhamdulilah': 'syukur',
 'anaka': 'anak',
 'ancur': 'hancur',
 'ane': 'saya',
 'aq': 'saya',
 'at': 'otomatis',
 'bangat': 'sangat',
 'banget': 'sangat',
 'bangg': 'abang',
 'bapa': 'bapak',
 'bapuk': 'buruk',
 'bbm': 'bensin',
 'bejek': 'gas',
 'bener': 'benar',
 'bener2': 'sangat',
 'berisik': 'bising',
 'best': 'bagus',
 'bg': 'abang',
 'bgs': 'bagus',
 'bgt': 'sangat',
 'bkn': 'bukan',
 'blkng': 'belakang',
 'blm': 'belum',
 'bngt': 'sangat',
 'bnyak': 'banyak',
 'bnyk': 'banyak',
 'boros': 'boros',
 'bos': 'bos',
 'br': 'baru',
 'brsk': 'bising',
 'bs': 'bisa',
 'bsa': 'bisa',
 'buat': 'untuk',
 'calsig': 'calya sigra',
 'ceper': 'rendah',
 'cm': 'cuma',
 'cmn': 'cuma',
 'cuan': 'untung',
 'cuman': 'cuma',
 'd': 'di',
 'dah': 'sudah',
 'dg': 'dengan',
 'dgn': 'dengan',
 'dh': 'sudah',
 'dhe': 'deh',
 'dl': 'dulu',
 'dlu': 'dulu',
 'dpt': 'dapat',
 'dr': 'dari',
 'dri': 'dari',
 'eee': 'eh',
 'elo': 'kamu',
 'emg': 'memang',
 'enak': 'nyaman',
 'enakan': 'nyaman',
 'enk': 'nyaman',
 'ente': 'kamu',
 'g': 'tidak',
 'ga': 'tidak',
 'gabisa': 'tidak bisa',
 'gaenak': 'tidak nyaman',
 'gaje': 'tidak jelas',
 'gajelas': 'tidak jelas',
 'gak': 'tidak',
 'gandos': 'bagus',
 'gapapa': 'tidak apa',
 'gasruk': 'gesek',
 'gatau': 'tidak tahu',
 'gausah': 'tidak usah',
 'geter': 'getar',
 'gimana': 'bagaimana',
 'gini': 'begini',
 'gitu': 'begitu',
 'gk': 'tidak',
 'glodakan': 'bising',
 'gmn': 'bagaimana',
 'gn': 'begini',
 'gocar': 'taksi',
 'good': 'bagus',
 'gpp': 'tidak apa',
 'grab': 'taksi',
 'gt': 'begitu',
 'gtu': 'begitu',
 'gtw': 'tidak tahu',
 'gua': 'saya',
 'gue': 'saya',
 'gw': 'saya',
 'hoax': 'bohong',
 'irit': 'hemat',
 'jd': 'jadi',
 'jdi': 'jadi',
 'jelek': 'buruk',
 'jlk': 'buruk',
 'jos': 'bagus',
 'josgandos': 'sangat bagus',
 'joss': 'bagus',
 'josss': 'bagus',
 'kagak': 'tidak',
 'kalo': 'kalau',
 'karna': 'karena',
 'karnakan': 'karena',
 'kaya': 'seperti',
 'kayak': 'seperti',
 'kedap': 'senyap',
 'kek': 'seperti',
 'kenceng': 'kencang',
 'keren': 'bagus',
 'keujanan': 'kehujanan',
 'kl': 'kalau',
 'klau': 'kalau',
 'klo': 'kalau',
 'knalpot': 'saluran buang',
 'knp': 'kenapa',
 'kpd': 'kepada',
 'krn': 'karena',
 'krna': 'karena',
 'kulo': 'saya',
 'kureng': 'kurang',
 'kyk': 'seperti',
 'laaa': 'lah',
 'lbh': 'lebih',
 'lelet': 'lambat',
 'lemot': 'lambat',
 'lg': 'lagi',
 'lmyan': 'cukup',
 'lo': 'kamu',
 'lu': 'kamu',
 'lum': 'belum',
 'lumayan': 'cukup',
 'mahal': 'mahal',
 'mantab': 'bagus',
 'mantap': 'bagus',
 'mas': 'abang',
 'matic': 'otomatis',
 'matik': 'otomatis',
 'mbak': 'kakak',
 'mending': 'lebih baik',
 'mgkn': 'mungkin',
 'mhl': 'mahal',
 'mmg': 'memang',
 'mngkn': 'mungkin',
 'mnurut': 'menurut',
 'mobi': 'mobil',
 'mreka': 'mereka',
 'mrh': 'murah',
 'mt': 'manual',
 'mtb': 'bagus',
 'mura': 'murah',
 'murah': 'murah',
 'mw': 'mau',
 'nanjak': 'tanjak',
 'napa': 'kenapa',
 'nemu': 'temu',
 'nga': 'tidak',
 'ngeden': 'berat',
 'ngga': 'tidak',
 'nggak': 'tidak',
 'ngk': 'tidak',
 'nipu': 'tipu',
 'nyaman': 'nyaman',
 'nyangkut': 'sangkut',
 'nymn': 'nyaman',
 'ok': 'bagus',
 'oke': 'bagus',
 'orag': 'orang',
 'org': 'orang',
 'pake': 'pakai',
 'pakek': 'pakai',
 'parah': 'sangat',
 'pdhl': 'padahal',
 'pegel': 'pegal',
 'pelg': 'pelek',
 'pesen': 'pesan',
 'pnp': 'penumpang',
 'q': 'saya',
 'review': 'ulasan',
 'rivew': 'ulasan',
 'rmh': 'rumah',
 'rugi': 'rugi',
 'sampe': 'sampai',
 'sat set': 'cepat',
 'satset': 'cepat',
 'seken': 'bekas',
 'shock': 'suspensi',
 'siang2': 'siang',
 'sihhh': 'sih',
 'sj': 'saja',
 'skrg': 'sekarang',
 'skrng': 'sekarang',
 'sm': 'sama',
 'sma': 'sama',
 'sok': 'suspensi',
 'sokbreker': 'suspensi',
 'sy': 'saya',
 'sya': 'saya',
 'tak': 'tidak',
 'tampa': 'tanpa',
 'tau': 'tahu',
 'taxi': 'taksi',
 'the': 'sangat',
 'tiper': 'tipe r',
 'tp': 'tapi',
 'tpi': 'tapi',
 'trs': 'terus',
 'trus': 'terus',
 'ttep': 'tetap',
 'ttg': 'tentang',
 'ttp': 'tetap',
 'tw': 'tahu',
 'udah': 'sudah',
 'udh': 'sudah',
 'udj': 'sudah',
 'ug': 'yang',
 'utk': 'untuk',
 'velg': 'pelek',
 'w': 'saya',
 'wkt': 'waktu',
 'worit': 'sepadan',
 'wort it': 'sepadan',
 'worth it': 'sepadan',
 'yg': 'yang',
 'yng': 'yang',
 'zonk': 'buruk'}
KOREKSI_SASTRAWI = {'asa': 'rasa',
 'awat': 'rawat',
 'dar': 'sekadar',
 'kebel': 'beli',
 'ken': 'ingin',
 'kenyam': 'nyaman',
 'kes': 'kesan',
 'mud': 'kemudi',
 'nyam': 'nyaman'}
KATA_KUNCI_MOBIL = set(['mobil',
 'lcgc',
 'ayla',
 'agya',
 'sigra',
 'calya',
 'brio',
 'karimun',
 'wagon',
 'datsun',
 'mesin',
 'setir',
 'bensin',
 'knalpot',
 'velg',
 'pelek',
 'ban',
 'suspensi',
 'kabin',
 'jok',
 'bagasi',
 'ac',
 'rem',
 'kopling',
 'gigi',
 'gas',
 'irit',
 'boros',
 'tanjak',
 'tol',
 'jalan',
 'dealer',
 'harga',
 'beli',
 'kredit',
 'cicil',
 'taksi',
 'service',
 'servis',
 'oli',
 'kualitas',
 'performa',
 'nyaman',
 'sempit',
 'bagus',
 'jelek'])
KATA_SPAM_REQUEST = set(['bahas',
 'next',
 'video',
 'giveaway',
 'cobain',
 'reviewin',
 'tanya',
 'info',
 'hadir',
 'mampir',
 'subs',
 'channel',
 'konten',
 'kapan',
 'tutorial'])
KATA_SENTIMEN_PENDEK = set({'aman',
 'bagus',
 'bising',
 'boros',
 'buruk',
 'cepat',
 'halus',
 'hemat',
 'kecewa',
 'keren',
 'kuat',
 'lambat',
 'lemah',
 'mahal',
 'mantap',
 'mewah',
 'mudah',
 'murah',
 'nyaman',
 'parah',
 'puas',
 'rugi',
 'rusak',
 'sempit',
 'stabil',
 'suka',
 'susah',
 'untung'})

KATA_POSITIF = set(['kuat',
 'tetep',
 'fungsional',
 'lunas',
 'ekonomis',
 'suka',
 'bgs',
 'fungsi',
 'senang',
 'laris',
 'mudah',
 'hebat',
 'sip',
 'tenang',
 'terjangkau',
 'sempurna',
 'keren',
 'mantep',
 'lancar',
 'elegan',
 'dahsyat',
 'mendingan',
 'aamiin',
 'canggih',
 'benar',
 'lega',
 'kebeli',
 'betul',
 'stabil',
 'responsif',
 'rekomendasi',
 'kokoh',
 'impian',
 'manteb',
 'masih',
 'seru',
 'rekomen',
 'bersukur',
 'lapang',
 'bangga',
 'kencang',
 'berkelas',
 'gandos',
 'bener',
 'bandel',
 'mantaf',
 'gampang',
 'mending',
 'lumayan',
 'alhamdulillah',
 'aman',
 'padan',
 'laku',
 'terbaik',
 'multifungsi',
 'adem',
 'top',
 'kece',
 'amin',
 'favorit',
 'mantul',
 'bersyukur',
 'puas',
 'lincah',
 'cukup',
 'enak',
 'tetap',
 'syukur',
 'setuju',
 'sepadan',
 'praktis',
 'tangguh',
 'optimal',
 'sesuai',
 'awat',
 'cakep',
 'ringan',
 'semoga',
 'pas',
 'terpercaya',
 'jangkau',
 'syukuri',
 'sepakat',
 'nyaman',
 'alhamdulilah',
 'istimewa',
 'bismillah',
 'gesit',
 'cocok',
 'terbantu',
 'prima',
 'manfaat',
 'menang',
 'impi',
 'oke',
 'jos',
 'mulus',
 'dingin',
 'imbang',
 'mewah',
 'empuk',
 'moga',
 'penting',
 'kenceng',
 'mantap',
 'murah',
 'mampu',
 'normal',
 'handal',
 'ngimbangin',
 'unggulan',
 'worth',
 'plong',
 'mengimbangi',
 'cepat',
 'luas',
 'wajar',
 'nikmat',
 'sanggup',
 'bantu',
 'baik',
 'bagus',
 'irit',
 'andal',
 'awet',
 'selamat',
 'manusiawi',
 'untung',
 'solusi',
 'halus',
 'hemat',
 'berkah'])
KATA_NEGATIF = set(['remeh',
 'glodakan',
 'tipis',
 'gerobak',
 'rugi',
 'susah',
 'kaleng',
 'belagu',
 'arogan',
 'lambat',
 'error',
 'lebay',
 'capek',
 'kurang',
 'kmahalan',
 'remuk',
 'lemot',
 'sombong',
 'buang',
 'tolol',
 'goyang',
 'plastik',
 'boyo',
 'reyot',
 'hina',
 'menyesal',
 'gembeng',
 'ngeden',
 'bising',
 'ribet',
 'kerupuk',
 'kecewa',
 'bermasalah',
 'jeleknya',
 'nyiksa',
 'berisik',
 'bapuk',
 'getar',
 'hancur',
 'ngelitik',
 'nyesel',
 'jelek',
 'buruk',
 'batal',
 'rombeng',
 'bacot',
 'kemahalan',
 'gagal',
 'sempit',
 'nipu',
 'overprice',
 'bocor',
 'ancur',
 'lemah',
 'kureng',
 'pegel',
 'bodoh',
 'hujat',
 'nyendat',
 'ringkih',
 'katrok',
 'minus',
 'loyo',
 'malu',
 'murahan',
 'ampas',
 'benci',
 'ngenes',
 'angkot',
 'hoax',
 'gaada',
 'ngehujat',
 'jebol',
 'ngotak',
 'mahal',
 'boros',
 'rentan',
 'boyot',
 'mual',
 'parah',
 'gasruk',
 'bcot',
 'rusak',
 'jlk',
 'mentok',
 'kopong',
 'keras',
 'kehujanan',
 'geter',
 'sampah',
 'limbung',
 'lelet',
 'odong',
 'glodak',
 'khongguan',
 'kepanasan',
 'panas'])
FRASA_POSITIF = ['luar biasa',
 'worth it',
 'lebih baik',
 'beli baru',
 'mending ambil',
 'mending beli',
 'tidak malu',
 'ga malu',
 'gak malu',
 'bukan gengsi',
 'tidak ada masalah',
 'tidak ada kendala',
 'tanpa masalah',
 'tanpa kendala',
 'tidak jelek',
 'ga jelek',
 'gak jelek',
 'tidak mahal',
 'ga mahal',
 'gak mahal',
 'tidak boros',
 'ga boros',
 'gak boros',
 'anti panas',
 'anti hujan',
 'tidak bising',
 'tidak berisik',
 'tidak rusak',
 'tidak nyesel',
 'tidak rugi',
 'tidak limbung',
 'tidak gasruk',
 'tidak mentok',
 'tidak rewel',
 'tidak getar',
 'tidak geter',
 'ga getar',
 'ga geter',
 'gak getar',
 'gak geter',
 'tidak hujan',
 'ga hujan',
 'gak hujan',
 'tidak kepanasan',
 'ga kepanasan',
 'tidak panas',
 'ga panas',
 'gak panas',
 'tidak kehujanan',
 'ga kehujanan',
 'aman aja',
 'aman aman',
 'ga ada geter',
 'gak ada getar',
 'tidak ada getar',
 'tidak kendala',
 'nggak kendala',
 'bisa beli',
 'kredit lunas',
 'getar mana',
 'geter mana',
 'mana getar',
 'mana geter',
 'siapa bilang',
 'kata siapa',
 'mana ada',
 'jangan salah',
 'salah besar',
 'tetep joss',
 'tetep jos',
 'tetep bagus',
 'tetep nyaman',
 'tetep aman',
 'tetep irit',
 'tetap joss',
 'tetap jos',
 'tetap bagus',
 'tetap nyaman',
 'tetap aman',
 'tetap irit',
 'masih bagus',
 'masih nyaman',
 'masih aman',
 'masih irit',
 'masih oke',
 'masih kencang',
 'paling irit',
 'paling nyaman',
 'paling murah',
 'paling bagus',
 'paling keren',
 'sangat nyaman',
 'sangat bagus',
 'sangat irit',
 'sangat murah',
 'sangat keren',
 'lebih nyaman',
 'lebih bagus',
 'lebih irit',
 'lebih murah',
 'lebih keren',
 'lebih luas',
 'cukup nyaman',
 'cukup bagus',
 'cukup irit',
 'cukup luas',
 'cukup aman',
 'aman nyaman',
 'nyaman aman',
 'enak nyaman',
 'aman kok',
 'bagus kok',
 'nyaman kok',
 'irit kok',
 'kuat kok',
 'ga ada masalah',
 'gak ada masalah',
 'ga masalah',
 'gak masalah',
 'ga nyesel',
 'gak nyesel',
 'ga rugi',
 'gak rugi',
 'yang penting',
 'yg penting',
 'jerih payah',
 'pala bapak']
FRASA_NEGATIF = ['tidak bagus',
 'kurang bagus',
 'tidak irit',
 'kurang irit',
 'tidak awet',
 'kurang awet',
 'tidak nyaman',
 'kurang nyaman',
 'ga nyaman',
 'gak nyaman',
 'tidak enak',
 'ga enak',
 'gak enak',
 'tidak laku',
 'ga laku',
 'gak laku',
 'tidak aman',
 'kurang aman',
 'tidak sanggup',
 'tidak mampu',
 'bukan mobil',
 'jangan beli',
 'kaleng kerupuk',
 'body kaleng',
 'kasta bawah',
 'kasta paling bawah',
 'uji mental',
 'menguji mental',
 'kurang dingin',
 'tidak dingin',
 'ga dingin',
 'gak dingin',
 'kurang mantap',
 'kurang mantep',
 'kurang fitur',
 'tidak ada wiper',
 'gaada wiper',
 'tanpa wiper',
 'over price',
 'kacang rebus',
 'batal beli',
 'urung beli',
 'tidak kuat',
 'ga kuat',
 'gak kuat',
 'kurang kuat',
 'kurang luas',
 'kurang lega',
 'kurang empuk',
 'ac kurang',
 'ac ga',
 'ac gak',
 'ac tidak',
 'sangat mahal',
 'terlalu mahal',
 'sangat boros',
 'terlalu boros',
 'sangat sempit',
 'terlalu sempit',
 'sangat bising',
 'terlalu bising']

# Tambahan berdasarkan kosakata keluhan yang muncul pada dataset otomotif.
# Kata umum tidak ditambahkan secara sembarangan; fokusnya pada istilah yang
# memiliki makna negatif dalam konteks kendaraan atau harga kendaraan.
KATA_NEGATIF.update({
    'primitif', 'kuno', 'ngeselin', 'najis', 'minim', 'paksa', 'ngoreng'
})
FRASA_POSITIF.extend([
    'tidak buruk', 'tidak terlalu mahal', 'tidak mahal sekali',
    'tidak jelek kok', 'tidak jelek sama sekali'
])
FRASA_NEGATIF.extend([
    'harga goreng', 'harga digoreng', 'fitur minim', 'minim aman',
    'pintu ringan', 'kualitas buruk', 'mesin getar', 'terlalu getar',
    'model kuno', 'head unit primitif', 'tidak nyaman', 'tidak aman'
])

KAMUS_SLANG_FRASA = {k: v for k, v in KAMUS_SLANG.items() if " " in k}
KAMUS_SLANG_KATA = {k: v for k, v in KAMUS_SLANG.items() if " " not in k}


def buat_preprocessor():
    stemmer = StemmerFactory().create_stemmer()
    stopword_asli = StopWordRemoverFactory().get_stop_words()
    stopword = {kata for kata in stopword_asli if kata not in KATA_PENTING}
    stopword.update(CUSTOM_STOPWORD)
    return stemmer, stopword


def normalisasi_teks(teks):
    for frasa in sorted(KAMUS_SLANG_FRASA, key=len, reverse=True):
        teks = re.sub(rf"(?<!\w){re.escape(frasa)}(?!\w)", KAMUS_SLANG_FRASA[frasa], teks)
    return " ".join(KAMUS_SLANG_KATA.get(kata, kata) for kata in teks.split())


def preprocess_teks(teks, stemmer, stopword, cache_stemming=None):
    cache = cache_stemming if cache_stemming is not None else {}
    teks_bersih = re.sub(r"[^a-zA-Z\s]", " ", str(teks)).lower()
    teks_bersih = re.sub(r"\s+", " ", teks_bersih).strip()
    teks_normal = normalisasi_teks(teks_bersih)
    tanpa_stopword = [kata for kata in teks_normal.split() if kata not in stopword]

    hasil_stem = []
    for kata in tanpa_stopword:
        if kata not in cache:
            cache[kata] = stemmer.stem(kata)
        hasil_stem.append(cache[kata])

    return " ".join(KOREKSI_SASTRAWI.get(kata, kata) for kata in hasil_stem)


def cek_kelayakan(teks):
    kata_kata = teks.split()
    token = set(kata_kata)
    if not kata_kata:
        return False
    if len(kata_kata) == 1:
        return kata_kata[0] in KATA_SENTIMEN_PENDEK
    ada_konteks = bool(token & KATA_KUNCI_MOBIL) or bool(token & KATA_SENTIMEN_PENDEK)
    ada_spam = bool(token & KATA_SPAM_REQUEST)
    return ada_konteks and not ada_spam


def hitung_skor_lexicon(teks, dengan_detail=False):
    teks_lower = str(teks).lower()
    token = set(teks_lower.split())
    skor_pos = 0
    skor_neg = 0
    detail_pos = []
    detail_neg = []

    # Prioritaskan frasa yang paling panjang. Setelah sebuah frasa cocok,
    # bagian tersebut ditutup agar kata di dalamnya tidak dihitung kembali
    # dengan polaritas berlawanan (mis. "tidak buruk" dan kata "buruk").
    frasa_berlabel = [(frasa, 'POSITIF') for frasa in FRASA_POSITIF]
    frasa_berlabel += [(frasa, 'NEGATIF') for frasa in FRASA_NEGATIF]
    teks_sisa = teks_lower
    for frasa, label in sorted(frasa_berlabel, key=lambda item: len(item[0]), reverse=True):
        pola = rf'(?<!\w){re.escape(frasa)}(?!\w)'
        if re.search(pola, teks_sisa):
            if label == 'POSITIF':
                skor_pos += 3
                if dengan_detail:
                    detail_pos.append(f'"{frasa}" (+3)')
            else:
                skor_neg += 3
                if dengan_detail:
                    detail_neg.append(f'"{frasa}" (+3)')
            teks_sisa = re.sub(pola, ' ', teks_sisa)

    token_sisa = set(teks_sisa.split())
    for kata in KATA_POSITIF:
        if kata in token_sisa:
            skor_pos += 1
            if dengan_detail:
                detail_pos.append(f'"{kata}" (+1)')
    for kata in KATA_NEGATIF:
        if kata in token_sisa:
            skor_neg += 1
            if dengan_detail:
                detail_neg.append(f'"{kata}" (+1)')

    return {
        "positif": skor_pos,
        "negatif": skor_neg,
        "detail_positif": detail_pos,
        "detail_negatif": detail_neg,
    }


def label_lexicon(teks):
    skor = hitung_skor_lexicon(teks)
    if skor["positif"] > skor["negatif"]:
        return "POSITIF"
    if skor["negatif"] > skor["positif"]:
        return "NEGATIF"
    return "NETRAL"
